### ISSUE TITLE
Cannot open a file

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/storj-mobile#15]
I simply cannot find a way to display a picture in the app.

Steps to reproduce:
1. Open the Pictures bucket
1. Tap on a file - nothing happens
1. Tap on the ellipses to show the action bar
1. Click on the download button - the file downloads successfully
1. Tap on the file - nothing happens...

**Comment by NikolaiYurchenko** [comment]
You probably have Android 6 or lower on your device. 
So we are receiving mimetype /octet-stream instead of image/ on this kind of devices and therefore unable to show image preview.

**Comment by kaloyan-raev** [comment]
Yes, I am on Android 6. I remember the android-libstorj library returned better mime types in the past. I'll check what went wrong.
